### ISSUE TITLE
cylinderFlap tutorial issue

### ISSUE THREAD

**Issue by munkapas** [precice/tutorials#243]
Hello,

The tutorial provided under the below link does not work:
https://github.com/precice/tutorials/tree/CoupledProblems2019/FSI/cylinderFlap/OpenFOAM-CalculiX

The solver errors out because there is no preciceDict file to be found in folder Fluid/system. I do not know what else may be missing besides this. Please verify if this tutorial can be run. If it cannot run, please provide a complete set of tutorial files that can be executed.

**Comment by uekerman** [comment]
Hi @munkapas :wave: 

Could I ask what is your motivation to run this specific branch? Is this to reproduce results from a publication?
If not, I would recommend to run the newest released version. Following instructions [in the docs](https://precice.org/tutorials.html). For an overview of compatible versions, see [the distribution](https://precice.org/installation-distribution.html).

If you really want to run this specific branch, you need an older version of the OpenFOAM adapter. Before this change: https://github.com/precice/openfoam-adapter/pull/105

**Comment by munkapas** [comment]
Hi Benjamin,

Thank you for looking into this. The main reason I wanted to run this tutorial is because it already worked for me previously. Actually, this was the only thing that worked for me using preCICE, after spending a lot of efforts in setting up and configuring preCICE - it was quite a while ago... Compiling, installing and setting up preCICE seems extremely complicated to me. The only way I could successfully configure preCICE was by following the steps outlined by Prof. Nilsson:
http://www.tfd.chalmers.se/~hani/wikis/haniWiki/index.php?title=Tips_and_tricks_/_CalculiX_/_Installation

However, that time I used a VM virtual machine running Ubuntu, when I could successfully configure preCICE for the first time. But after some time, my VM virtual machine crashed and all files were lost. Then I configured preCICE again, and after a short time the VM crashed again, and all files were lost again. I did not see a value to further experiment with this then. Recently, I got access to VDI environment which seems to be much more stable than a VM virtual machine, so I am again trying to configure preCICE. But as I mentioned it seems extremely complicated process to me and I do not see any good chances for success unless I follow the previously working setup outlined by Prof. Nilsson. I know it is using outdated versions, but at least I see a chance I could configure it successfully. However, the tutorial files in the package CoupledProblems2019 are not the same that I used previously, that is why I submitted this question here. I completed the setup of preCICE, OpenFOAM and CalculiX, but I cannot verify if my setup works, because the tutorial does not work (missing preciceDict in Fluid/system folder, and potentially other issues).

**Comment by MakisH** [comment]
Hi @munkapas,

if you only want to run tutorials, then there is no reason to try running this 2+ year-old setup. A lot has changed in between and hopefully a lot is now much easier.

I would strongly encourage you to stick to our official documentation and keep in mind that any third-party resources will almost certainly be outdated. There is now a [demo virtual machine](https://precice.org/installation-vm.html) with everything installed and a [quickstart guide](https://precice.org/quickstart.html). We are now in preCICE v2 (instead of v1 in the link you posted) and we have vastly reorganized and simplified our tutorials. The "cylinderFlap" tutorial is now the [Turek Hron FSI3 tutorial](https://precice.org/tutorials-turek-hron-fsi3.html).

By the way, you could argue that this is a bad sign for reproducibility. And you would be right, but that's why we created the [distribution](https://precice.org/installation-distribution.html) of all components that @uekerman already mentioned above. We are always very interested on such feedback, but many of the issues you mention we have already improve in newer versions.

I don't think we can do something about this specific issue, as we cannot support older versions. However, we are always very happy to help the community in our [preCICE forum](https://precice.discourse.group/).

**Comment by munkapas** [comment]
I am now trying to install the latest preCICE following the official documentation. My initial impression is that it will require reading through a lot of details, and I will most likely end up with confusions and unsuccessful attempts.
I am running complex OpenFOAM and CalculiX models every day, but I do not have a way to couple them for FSI simulations. I am running simple tutorials only to verify if everything is configured properly.

**Comment by uekerman** [comment]
As @MakisH pointed out, many things are much simpler now and better documented. We are happy to help you in the forum if you run into problems. And we are interested in case you are missing information.
