### ISSUE TITLE
The `setup-dumux.sh` couldn't install DuMuX properly

### ISSUE THREAD

**Issue by Fujikawas** [precice/tutorials#517]
With the `setup-dumux.sh` in the tutorial case `two-scale-heat-transfer`, the modules like `dune::grid`, `dune::geometry ` couldn't be found by dumux so the solver installation with this script would fail. Might because the dynamic/shared libs are not built for these modules.

- Tutorials state (last commit / release): last commit
- Versions of solvers and adapters used: DuMuX 3.8 according to the `setup.sh` script,
- preCICE version: latest `develop` branch
- Log files: [installdumux.log](https://github.com/precice/tutorials/files/14916647/installdumux.log)

**Comment by IshaanDesai** [comment]
After some debugging, it appears that it is important to set `DUNE_CONTROL_PATH` to `.` (the current directory). Using this, I see the following error:

```bash
ERROR: multiple definition of module dune-geometry
previous defined in:
  /home/desaiin/tutorials/two-scale-heat-conduction/dune-geometry/dune.module
redefined in:
  /home/desaiin/tutorials/two-scale-heat-conduction/dune-common/build-cmake/dune-env/lib/dunecontrol/dune-geometry/dune.module
Execution of dunecontrol terminated due to errors!
```

**Comment by MakisH** [comment]
Could this be related to conflicts with the dune (not dumux) adapter?

**Comment by IshaanDesai** [comment]
> Could this be related to conflicts with the dune (not dumux) adapter?

Potentially yes. But we investigated further and have concluded that these types of errors will pop up if a second installation of dune modules exists on a machine. @mathiskelm will push a fix soon, which we will then test and finalize.

**Comment by mathiskelm** [comment]
If the DUNE configuration (dunecontrol) detects another installation in the paths specified in `DUNE_CONTROL_PATH` or in default directories through CMake/pkgconfig, it can lead to issues as in the `installdumux.log` in this issue. The former we can limit by using a path of `.`, but for the latter we would resort to a warning in the tutorial's README.
The second error related to multiple module definition is caused by module files duplicated into `dune-common/build-cmake/dune-env/lib/dunecontrol` by dunecontrol. As it's not clear when and why they sometimes are found after a successful run of dunecontrol, I would change the setup script to clean said directory in between the two dunecontrol runs.
I'm also looking to add some options to the `installdumux.py` script which would simplify the setup script, but with the changes in #518 the `setup-dumux.sh` script should be more robust.
