### ISSUE TITLE
Explain configuration with comments in xml files

### ISSUE THREAD

**Issue by fsimonis** [precice/tutorials#75]
As the tutorials will be used primarily by new preCICE users, there should be some explanation of the setup directly inside the configuration files.

This is feedback from the Workshop 2020.

**Comment by uekerman** [comment]
I think we should only do this for the first tutorial that users run, so following our current plans only "OpenFOAM-FEniCS". Otherwise, it gets too much. Once you know how the config roughly works comments are annoying as they need a lot of space and you cannot "comment over comments" in xml (I hope what I mean is understandable). I always found the [comments in ElasticTube](https://github.com/precice/elastictube1d/blob/master/cxx/precice-config.xml) too much.

**Comment by MakisH** [comment]
Discussion from coding days:
- After moving the documentation to a unified place, we could streamline the information so that users are more familiar with the configuration and the resources. This will be done independently of this issue.
- We don't want to spoil all the configuration files with comments, as they are prone to deprecation.
- There is always the [web-based tutorial](https://run.precice.org/) that focuses a lot on the XML config.

Decision: We close this as "wont-fix", we fix it in other ways.
